### ISSUE TITLE
Csharp (C#)

### ISSUE THREAD

**Issue by willowvil** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#27]
Hello,

I´m not able to set up the transition working with a ListView. Here is my code:

_Page 1:_
```
myList.ItemSelected += (sender, e) =>
            {
                var item = (Item)SelectedItem;
                SharedTransitionNavigationPage.SetTransitionSelectedGroup(this, item.id);
                App.Current.MainPage.Navigation.PushAsync(new Page2(), true);
            };
```

_ViewCell:_
```
var myImage = new CachedImage();
Plugin.SharedTransitions.Transition.SetName(myImage, "image");
Plugin.SharedTransitions.Transition.SetGroup(myImage, **???????**);
```

_Page 2:_
```
var myImage = new CachedImage();
Plugin.SharedTransitions.Transition.SetName(myImage, "image");
```

Thank you!

**Comment by GiampaoloGabba** [comment]
During your `ItemSelected` event you are setting the `SelectedGroup` with `item.id`
`SharedTransitionNavigationPage.SetTransitionSelectedGroup(this, item.id);`

So in your ViewCell you need to set group value with `item.id` too

The `SelectedGRoup` property needs to match the Group property in the selected cell, otherwise the plugin cant find what element need to be shared between the transition.

[Here an example](https://github.com/GiampaoloGabba/Xamarin.Plugin.SharedTransitions/tree/master/src/Sample/TransitionApp/TransitionApp/Views/Listview) using listview with MVVM

[Here an example](https://github.com/GiampaoloGabba/Xamarin.Plugin.SharedTransitions/tree/master/src/Sample/TransitionShellApp/TransitionShellApp/Views/Listview) with using Listview with `ItemSelected` event (inside a Shell)
