### ISSUE TITLE
Can it work with Shell GoToAsync() ?

### ISSUE THREAD

**Issue by jmkyarrow** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#37]
### Expected Behavior
When navigating between pages using Shell.Current.GoToAsync(), there should be a transition as specified.

### Actual Behavior
The navigation isn't animated and just cuts from one page to another.

**Comment by GiampaoloGabba** [comment]
Well, honestly, i have never, ever used `Shell` in my apps outside the demo for this plugin :(
Do you mind to create a simple repro of this issue so i can fork it and work on the Shell Renderer to make it work in such scenario?

Thank you

**Comment by GiampaoloGabba** [comment]
I made some investigations regarding this issue.
With relative routes (not using the // prefix) everything is working fine, i have updated the shell demo with a `GotoAsync` between the `ImageFromPage` and `ImageToPage`.

Unfortunately, if you are using absolute routes (with // prefix), the shared transition cannot work because within an absolute navigation the new page will replace the navigation stack. This means that every information about the views to transition are destroyed.

### [More info](https://github.com/xamarin/Xamarin.Forms/issues/5790) from the Xamarin.Forms repository:

- **route**
this will search relative to current position and will then go up the hierarchy until a route is found
_page will be pushed to stack_

- **/route**
this will search from the root down the hierarchy until a page is found
_page will be pushed to stack_

- **//route**
this will search relative to current position and will then go up the hierarchy until a route is found
_page will replace the stack_

- **///route** (think of this like //root/route/)
this will search from the root down the hierarchy until a page is found
_page will replace the stack_


If you are using relative routes and still shared transitions doesnt work, please post a repro so i can find the problem :)

**Comment by RGBPlaza** [comment]
Do you think it will work with the new .. notation?

**Comment by jmkyarrow** [comment]
Thank you for your help, it's working now using relative routes, I really appreciate your effort :) 
Do you think there would be a way to have the background animation transition on absolute routes even though individual elements don't work?
