### ISSUE TITLE
Changing aspect ratio in the transition results in weird glitch on iOS

### ISSUE THREAD

**Issue by vniehues** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#9]
## Bug Information

While the transition seems to animate the new bounds and the new aspect ratio on Android, on iOS it only transitions the position and then snaps to the new bounds and aspect ratio.

Version Number of Plugin: 1.0.0.1

### Steps to reproduce the Behavior
Create a solution with a BindableLayout and a Second Page where you pass the image (advanced transitioning)

### Expected Behavior
like on Android. -> Image changes bounds and aspect ratio while transitioning

### Actual Behavior
image transitions using the old aspect ratio and then snaps to the new aspect ratio

### Workaround i'm currently using
Make the source and destination image have the same height- & widthrequest. 
Layout image in destination page after the transition.

### Screenshots
Bug looks like this:
![bug](https://user-images.githubusercontent.com/28765921/56825038-568cf580-6858-11e9-997d-5f6e744b7068.gif)
Workaround looks like this:
![workaround](https://user-images.githubusercontent.com/28765921/56825039-568cf580-6858-11e9-9011-9d74731b17ae.gif)

**Comment by GiampaoloGabba** [comment]
umm.. interesting. When i developed this i tried this scenario and was working. 
The snapshot code for images is a bit clunky and i suspect with the new xamarin.iOS versions isnt working well.

would you mind to upload your test project? so i'll work directly on it

**Comment by vniehues** [comment]
Yes I will try to upload a test project later today. 
Will comment here with a link asap :)

**Comment by vniehues** [comment]
The test project is located under this link.
https://www.dropbox.com/s/fqr9xg8dije27b9/TestProject_SharedTransitions.zip?dl=0

**Comment by viniciuslln** [comment]
I have similar issue with android
video:
https://1drv.ms/v/s!ApSKgKoPus5HlKt6j-MCGI-JI9O7xg

And same Workaround fixing height- & widthrequest :)

**Comment by vniehues** [comment]
@Evolutionlab Do you have any news on this? Currently im lacking the time to look into it myself but i'll let you know here, if i have a chance to look at it :)

**Comment by vniehues** [comment]
@Evolutionlab I tinkered around with the project but unfortunately I couldn't find any possible solutions.

**Comment by GiampaoloGabba** [comment]
In IOS, the shared transitions works by taking a snapshot of the starting view and moving it where the final view is placed, modifying the size if needed. The resizing is made by keeping the aspect ratio. 

When transition ends, the starting view is cleared and the destination view will remain to screen: this is producing the glitch you see. To make it simple: in order to prevent glitch, starting and ending views need to have the same aspect ratio.

At the moment i cant crop and modify the aspect ratio while transitioning. sure, i can work on aspect ratio, maybe adding a new bindable property, but the crop... i don't know if its possible at least in ios.

Btw in android should work, in your example app Android is fine, so we need to check the code used in the second example you posted

**Comment by GiampaoloGabba** [comment]
with the latest commit this should have been resolved. I'll create a new nuget package soon
